# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

r:
  - devel

os:
  - linux
  #- osx

r_github_packages: snoweye/pbdZMQ

sudo: required
